### PR TITLE
Uplands quests + patchable adjustment

### PR DESCRIPTION
**Pull request by Haaxor1689**

### CODE REVIEW

**Comment by Gurky-Kronos** [comment]
I noticed [50063] = "Intact Orc Head", was removed from the items,. Just curious on this, wondering if something was done wrong.

**Comment by Haaxor1689** [comment]
It was incorrect, that id refers to [Intact Human Head](https://database.turtle-wow.org/?item=50063). I can also add the alliance disguise quest later but right now I have no way of checking it in-game.

**Comment by shagu** [comment]
Can you please elaborate where you hit an issue with patchtable that would require that change?

**Comment by Haaxor1689** [comment]
[This quest](https://database.turtle-wow.org/?quest=6321) was updated on turtle to allow all races so I added it here. In the `pfQuest` db in the next is only `6323` and in the turtle one I added all of the quests form the chain `{ 6323, 6322, 6324 }`.

In this case the `patchable` just crashes and breaks the whole `pfQuest-turtle` db.

```lua
  [6321] = {
    ["end"] = {
      ["U"] = { 2226 },
    },
    ["lvl"] = 10,
    ["min"] = 10,
    ["next"] = 6323,
    ["race"] = 16,
    ["start"] = {
      ["U"] = { 6389 },
    },
  },
```

```lua
  [6321] = {
    ["start"] = {
      ["U"] = { 6389 },
    },
    ["end"] = {
      ["U"] = { 2226 },
    },
    ["obj"] = {
      ["I"] = { 16209 },
    },
    ["race"] = 434,
    ["lvl"] = 10,
    ["min"] = 10,
    ["next"] = { 6323, 6322, 6324 },
  },
```

**Pull request merged**
