### PR TITLE
Added Teldrassil quests

### PR DESCRIPTION
**Pull request by IcemanHHW**
Quests:
- A Meeting With Adaena
- Securing Darnassus
- Brannol's Sewing Kit
- A Decisive Blow
- Unforseen Consequences
- Tasala's Word
- Rooting Out Corruption

NPC's:
- Brannol Eaglemoon
- Adaena Oakleaf
- Sentinel Danala
- Malos Lunarspear
- Distorted Treant
- Tesala Whitefeather

Objects:
- Brannol's Sewing Kit

Items:
- Brannol's Sewing Kit
- Withered Roots

### CODE REVIEW

**Comment by shagu** [comment]
Thanks, but you don't need to add NPCs that are already existing in vanilla.
The NPC `Brannol Eaglemoon` is already part of the pfQuest database and should not be added here.

**Comment by IcemanHHW** [comment]
Ah right, bit stupid from my part. This has been fixed

**Comment by IcemanHHW** [comment]
Just realised I need to add the race as well to the quests. So I'll close this for now until I figure out which race value is for the Alliance

**Comment by shagu** [comment]
Races are a bitmask that you can find the values here: [pfQuest Bitmasks](https://github.com/shagu/pfQuest/blob/master/database.lua#L303-L312)
Just add up the values you need from there.

Custom races like Goblins and Highelves don't have a race,
and use the generic race of their faction:
- Alliance = 77
- Horde = 178

**Comment by shagu** [comment]
Also if the quests you added won't show up for you, then you might need to click "Reset Cache" in the pfQuest settings.
You won't lose any progress by doing so. It just clears the cache that is used to map quest-titles to quest-ids.

**Comment by IcemanHHW** [comment]
Thanks Shagu, all issues are fixed now

**Comment by shagu** [comment]
Thanks for your contribution :rocket:

**Pull request merged**
